import urllib.request
import json
import uuid
import time

BASE_URL = "http://3.110.188.91"

print(f"=== Testing Full Speech Transcription & Agent Note Generation Cycle ===")

# 1. Create Session
req = urllib.request.Request(f"{BASE_URL}/session", data=b"", method="POST")
session = json.loads(urllib.request.urlopen(req, timeout=10).read().decode("utf-8"))
sid = session["session_id"]
print(f"[1] Created Session ID: {sid}")

# 2. Upload Chunk 1
with open("test_speech.wav", "rb") as f:
    audio_data = f.read()

def upload_chunk(chunk_index):
    boundary = "----SpeechLekhaBoundary" + uuid.uuid4().hex
    body = (
        f"--{boundary}\r\n"
        f'Content-Disposition: form-data; name="file"; filename="chunk_{chunk_index}.wav"\r\n'
        f"Content-Type: audio/wav\r\n\r\n"
    ).encode("utf-8") + audio_data + f"\r\n--{boundary}--\r\n".encode("utf-8")

    creq = urllib.request.Request(
        f"{BASE_URL}/chunk/{sid}",
        data=body,
        headers={"Content-Type": f"multipart/form-data; boundary={boundary}"},
        method="POST"
    )
    return json.loads(urllib.request.urlopen(creq, timeout=30).read().decode("utf-8"))

print("[2] Uploading Chunk 1 (Audio with speech: 'Today we are studying calculus...')...")
res1 = upload_chunk(1)
print(f"    Chunk 1 Transcribed: '{res1.get('text')}'")

print("[3] Uploading Chunk 2 (Triggers Agent Cycle on fine-tuned LLM)...")
res2 = upload_chunk(2)
print(f"    Chunk 2 Transcribed: '{res2.get('text')}'")

print("[4] Waiting for Ollama Qwen2.5-1.5B agent cycle to generate notes...")
for i in range(25):
    time.sleep(2)
    files = json.loads(urllib.request.urlopen(f"{BASE_URL}/files/{sid}", timeout=10).read().decode("utf-8"))
    tree = files.get("tree", [])
    print(f"    [T+{i*2+2}s] Files present: {tree}")
    if len(tree) > 1 or any(f != "00-index.md" for f in tree):
        print(f"    --> Detected new note files generated by Agent!")
        break

# 5. Check File Tree and Note Content
files = json.loads(urllib.request.urlopen(f"{BASE_URL}/files/{sid}", timeout=10).read().decode("utf-8"))
print(f"\n[5] Note Files in Session: {files.get('tree')}")
for filename in files.get("tree", []):
    content = files.get("files", {}).get(filename, "")
    print(f"\n--- File: {filename} ---\n{content}\n-------------------------")

# 6. End Session and trigger Finalizer
print("\n[6] Ending Session and triggering Lambda Finalizer...")
end_req = urllib.request.Request(f"{BASE_URL}/session/{sid}/end", data=b"", method="POST")
end_resp = json.loads(urllib.request.urlopen(end_req, timeout=15).read().decode("utf-8"))
print(f"[7] Session End Result: {end_resp}")

print("\n=== Test Completed Successfully! ===")
